### ISSUE TITLE
Terminal color escape sequences appear in errors output

### ISSUE THREAD

**Issue by moroshko** [elm-lang/elm-lang.org#427]
[Screenshot](https://dl.dropboxusercontent.com/u/1893981/Screenshots/vmf-.png)

It would be nice to transform things like `[33mcountry[0m` to a browser friendly version like `<span style="color: red;">country</span>`.

**Comment by evancz** [comment]
Okay, should have a partial fix. It does not do full highlighting though, that's a larger change that will happen longer term.

**Comment by moroshko** [comment]
@evancz When can we expect this fix to be deployed?

**Comment by evancz** [comment]
The partial fix was deployed when I posted. The bigger fix, I'm not sure. Probably needs to wait until the next release of the compiler to get some support in there.

**Comment by jvoigtlaender** [comment]
So the partial fix doesn't fix @moroshko's original problem? I, at least, still see the `[33m` and `[0m` symbols at http://elm-lang.org/try.

**Comment by evancz** [comment]
Can I get a http://sscce.org/ ? Maybe I'm not running the correct thing.

**Comment by evancz** [comment]
Oh, I got it now!

**Comment by evancz** [comment]
Okay, fixed, it was a bit trickier than I thought.

**Comment by moroshko** [comment]
Thanks Evan, looks great now!

**Comment by evancz** [comment]
No problem, thanks for the report!
